language: rust

env: TYPE=default RUST_BACKTRACE=1

rust:
  - "1.28.0"
  - stable
  - beta
  - nightly

sudo: false

cache: cargo

install:
  - cargo build -v

script:
  - cargo test -v

compiler:
    - clang
