[package]
name = "autograd"
version = "0.7.0"
authors = ["perrier1034 <janne.dc.ib.sa@gmail.com>"]

repository = "https://github.com/raskr/rust-autograd"
keywords = ["numerics", "machine-learning", "ndarray", "multidimensional", "neural-network"]
license-file = "LICENSE"
readme = "README.md"
description = "Tensors and computation graphs in Rust mimicking TensorFlow and Theano"
documentation = "https://docs.rs/autograd/"

[dependencies]
rand = "0.3.15"
ndarray = { version = "0.10.11" }
cblas-sys = { version = "0.1.4", optional = false, default-features = true }
blas-src = { version = "0.1.2", default-features = true, features = ["openblas"] }
#openblas-src = { version = "0.5.6", default-features = true, features = ["cblas", "system"] }
glob = "0.2"
rayon = "0.8.2"
libc = "0.2"
openblas-src = "0.5.6"

[build-dependencies]
cc = "1.0"

[lib]
name = "autograd"
path = "src/lib.rs"

[[example]]
name = "mlp_mnist"
path = "examples/mlp_mnist.rs"

[[example]]
name = "lstm_lm"
path = "examples/lstm_lm.rs"
