[package]
name = "autograd"
version = "0.5.0"
authors = ["perrier1034 <janne.dc.ib.sa@gmail.com>"]

repository = "https://github.com/perrier1034/rust-autograd"
keywords = ["numerics", "machine-learning", "ndarray", "multidimensional", "neural-network"]
license-file = "LICENSE"
readme = "README.md"
description = "A toy library to run computation graphs mimicking TensorFlow and Theano"
documentation = "https://docs.rs/autograd/"

[dependencies]
rand = "0.3.15"
ndarray = { version = "0.10.11" }
glob = "0.2"
fnv = "1.0.5"
# blas-sys = { version = "0.6", default-features = true, features = ["openblas"] }
rayon = "0.8.2"

[lib]
name = "autograd"
path = "src/lib.rs"

[[example]]
name = "mlp_mnist"
path = "examples/mlp_mnist.rs"

[[example]]
name = "lstm_lm"
path = "examples/lstm_lm.rs"
