name: build

on: [push, pull_request]

jobs:
  build:

    name: Rust-${{ matrix.rust }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1

    strategy:
      matrix:
        rust:
          - stable
          - nightly
        os: [ubuntu-latest, windows-latest, macos-10.15, macos-11]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - name: cargo build
      run: cargo build -v
    - name: cargo test
      run: cargo test -v
      continue-on-error: ${{ matrix.rust == 'nightly' }}

    - name: cargo test (blas=intel-mkl, ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: cargo test --lib -v --features blas,intel-mkl
      continue-on-error: ${{ matrix.rust == 'nightly' }}

    - name: cargo test (blas=openblas, ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: cargo test --lib -v --features blas,openblas
      continue-on-error: ${{ matrix.rust == 'nightly' }}

    - name: cargo test (blas=accelerate, macos-10.15)
      if: matrix.os == 'macos-10.15'
      run: cargo test -v --features blas,accelerate
      continue-on-error: ${{ matrix.rust == 'nightly' }}

    - name: cargo test (blas=accelerate, macos-11)
      if: matrix.os == 'macos-11'
      run: cargo test -v --features blas,accelerate
      continue-on-error: ${{ matrix.rust == 'nightly' }}

    - name: cargo test (blas=intel-mkl, windows-latest)
      if: matrix.os == 'windows-latest'
      run: cargo test -v --lib --features blas,intel-mkl
      continue-on-error: ${{ matrix.rust == 'nightly' }}

    - name: cargo test (blas=openblas, windows-latest)
      if: matrix.os == 'windows-latest'
      run: cargo test -v --lib --features blas,openblas
      continue-on-error: true # error: Non-vcpkg builds are not supported on Windows. You must use the 'system' feature.