name: Main

on: [push, pull_request]

jobs:
  build:

    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build
      run: cargo build -v
    - name: Run tests
      run: cargo test -v
      continue-on-error: ${{ matrix.rust == 'nightly' }}
    - name: Run tests (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: cargo test -v -blas,intel-mkl
      continue-on-error: ${{ matrix.rust == 'nightly' }}
    - name: Run tests (macos-latest)
      if: matrix.os == 'macos-latest'
      run: cargo test -v -blas,accelerate
      continue-on-error: ${{ matrix.rust == 'nightly' }}
    - name: Run tests (windows-latest)
      if: matrix.os == 'windows-latest'
      run: cargo test -v -blas,intel-mkl
      continue-on-error: ${{ matrix.rust == 'nightly' }}
